# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: My first github action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: install
      run: yarn install
    - name: build
      run: yarn build
    - name: Run unit tests
      run: yarn test
    - name: Run e2e tests
      run: yarn test:e2e
    - name: reporting test results
      # You may pin to the exact commit or the version.
      # uses: mikepenz/action-junit-report@5f47764eec0e1c1f19f40c8e60a5ba47e47015c5
      uses: mikepenz/action-junit-report@v4.1.0
      if: always()
      with:
        report_paths: 'reports/*.xml'
